name: "Test"
on:
  # pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: cachix/install-nix-action@v21
    - uses: cachix/cachix-action@v12
      with:
        name: cclaw
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    #- run: for f in $(nix-instantiate); do echo $f; cat $f; done
    - run: nix build .#gf-with-rgl .#pythonWithPGF
    # - run: nix-shell --run "echo OK"
